### ISSUE TITLE
Cannot create a swarm

### ISSUE THREAD

**Issue by robevans** [docker/swarm-library-image#1]
Hi,

I'm trying to get a swarm cluster up and running but seemingly falling at the first hurdle.  After running:

```
docker run --rm swarm create
```

I get the following error:

```
time="2015-02-27T17:36:20Z" level=fatal msg="Post https://discovery-stage.hub.docker.com/v1/clusters: dial tcp: lookup discovery-stage.hub.docker.com: no such host"
```

And the RHEL6.5 virtual machine I was running on crashed shortly after.   Any idea what could be going on here?

I've also seen a slightly different error when running the swarm image:

```
time="2015-02-27T17:49:01Z" level=fatal msg="Post https://discovery-stage.hub.docker.com/v1/clusters: dial tcp: i/o timeout"
```

**Comment by grr89** [comment]
i have same problem

**Comment by vieux** [comment]
please open your issue on https://github.com/docker/swarm
