### ISSUE TITLE
Swarm image in Docker 1.12.3

### ISSUE THREAD

**Issue by antoinetran** [docker/swarm-library-image#12]
Hi,

We tried to deploy Swarm the same way we did in Docker 1.11. We didn't manage to make overlay work. The question is: have anyone tried in Docker 1.12.3? We tried in Docker 1.12.3. Without token or TLS for now.

The scenario is as such: we have 3 nodes in CentOs7, we deployed:

- node1:

 Swarm manager and consul (we tried [progrium/consul/](https://hub.docker.com/r/progrium/consul/)) and [consul](https://hub.docker.com/_/consul/))
If I remember correctly:
```
docker run -d -p 4000:4000 swarm manage -H :4000 --replication --advertise <Node1LocalIp>:4000 consul://<Node1LocalIp>:8500 
docker run -d -p 8500:8500 progrium/consul -server -bootstrap
```

- node2 and 3: Swarm agent
`docker run -d swarm join --advertise=<LocalIp>:2375 consul://<Node1LocalIp>:8500`

All nodes have open iptables with:
`sudo iptables -I INPUT <last line before REJECT> -j ACCEPT`
and Docker is configured to listen in 2375/Tcp in their local IP, with cluster configuration as such:
`ExecStart=/usr/bin/docker daemon -H unix:// -H tcp://<Node1LocalIp>:2375 --cluster-store=consul://<Node1LocalIp>:8500 --cluster-advertise=eth0:2375`

We launched 2 containers CentOs7, one each in node 2 and 3:
```
docker run -H <Node1LocalIp>:4000 --rm -ti --net=TestNetwork --name Test1 --hostname Test1 centos:7
docker run -H <Node1LocalIp>:4000 --rm -ti --net=TestNetwork --name Test2 --hostname Test2 centos:7
```
Ping failed: `ping Test2` in Test1 and `ping Test1` in Test2 failed with no route to host. But if launched in the same Docker host, both containers can ping each other.

However, doing the exact same thing (container in separate Docker host) works in Docker downgraded in 1.11. The ping works.

**Comment by antoinetran** [comment]
UPDATE: with docker-ce-17.03.1 and Swarm 1.2.6, it works approximately. Please refer to https://github.com/docker/libnetwork/issues/962. Randomly, we cannot ping between containers, unless we restart the machine. When this happen, it is related to all containers in the machine.

**Comment by nishanttotla** [comment]
@antoinetran closing this issue since it's being tracked elsewhere.
