### ISSUE TITLE
docker network create overlay not working in version 1.2.8

### ISSUE THREAD

**Issue by Noodle05** [docker/swarm-library-image#16]
Trying to upgrade to swarm 1.2.8. But create overlay network remotely not working any more.

Reproduce steps
1. Deploy consul as KV store.
2. Deploy swarm:1.2.8 as manager on one node
3. Deploy swarm:1.2.8 as agent on multiple nodes.
4. Run command "docker -H tcp://localhost:3376 network create -d overlay test-net" on manager node works.
5. Run command "docker -H tcp://`hostname`:3376 network create -d overlay test-net" on manager node give "This is not swarm manager" error message.
6. Run command "docker -H tcp://<manager IP>:3376 network create -d overlay test-net" on any node will give same error.

Docker version: 17.0.6.0-ce
Host OS: centos 7

This is not an issue on swarm:1.2.7

**Comment by justincormack** [comment]
Classic Swarm is now archived see docker/classicswarm#2986
