### ISSUE TITLE
MacVlan swarm scoped

### ISSUE THREAD

**Issue by antoinetran** [docker/swarm-library-image#17]
Hi,

I would like to make an improvement proposal of supporting MacVlan in swarm scope, in the same way that Swarm mode can now handle, since 17.06 ([http://collabnix.com/docker-17-06-swarm-mode-now-with-macvlan-support/](http://collabnix.com/docker-17-06-swarm-mode-now-with-macvlan-support/)).

The issue is that in order to deploy containers with MacVlan applied, Swarm needs to look at the network to attach and this network is local scoped:
```
[trana@in1l2psim-s00 ~]$ dswarm network ls|grep integ
e17142f84a4c        in1l2pdck-s00.l2pf.integ1.mtg/bridge                          bridge              local
6d9eaeb2a53c        in1l2pdck-s00.l2pf.integ1.mtg/host                            host                local
d2ad8b53e077        in1l2pdck-s00.l2pf.integ1.mtg/integ1mti1fci_brnet             bridge              local
035a2f3e1fbf        in1l2pdck-s00.l2pf.integ1.mtg/integ1mti1fci_pubnet            macvlan             local
```
If the network name is unique (so deployed to only one machine), Swarm can deploy it. But in the contrary Swarm cannot find the correct network id.

I know Swarm classic is deprecated but I believe there are still lots of projects like us that cannot migrate to Swarm mode yet (due missing feature, and now because kubernetes or docker kubernates is the future).

Thank you.

**Comment by antoinetran** [comment]
When I create a swarm scoped network, docker says that swarm (mode) is not enabled. What I would like if possible is that docker also recognizes Swarm classic.

**Comment by justincormack** [comment]
Classic Swarm is now archived see docker/classicswarm#2986
