### ISSUE TITLE
Build Swarm image  and Run error : no such file or directory

### ISSUE THREAD

**Issue by chengjingtao** [docker/swarm-library-image#5]
I modified  the code of swarm  and build  successful .
Then I clone this project to my local disk ,  relplace  executable file into `my swarm file` ,  do the command  next

```
sudo docker build -t chengjt/swarm:local .
```

then  run it 

```
sudo docker run    chengjt/swarm:local
```

But docker can't start it

```
no such file or directory
Error response from daemon: Cannot start container 4bf15703a3be9819706bd8ec841906b19dfc9317b71b82f37189c7acd5489d55: [8] System error: no such file or directory
```

Directly executing  `my swarm file`   is normal .

And using `official swarm file` , image building  and container  runing is normal too .
Even, I write a simple  hello world program and rename to swarm and build , run ..  it is normal too ...

what's wrong with my swarm program ? why does docker tells me " no such file or directory ? "

Thank you so much.

Docker version :  1.8.3, build f4bf5c7
go version :  go1.4.2 linux/amd64

**Comment by vieux** [comment]
@linecheng you need to compile swarm statically. since the Dockerfile is using `FROM scratch` there is nothing in the container, not even the libc

**Comment by chengjingtao** [comment]
hai , @vieux,
I am so sorry for replying so lately . 
I   tried  that and it works well .
Thank you very much .
