### ISSUE TITLE
1.2.0rc1 volumes not updating correctly

### ISSUE THREAD

**Issue by francisjeanneau** [docker/swarm-library-image#7]
### Using swarm:1.2.0rc1

Volumes are not updated correctly unless you restart the swarm containers.

Specifically, if I modify a text file on host machine by adding (or deleting) characters, the same file in the volume will have space at the end (or will be cropped) by the same amount of characters that I added (or removed).

**Comment by dongluochen** [comment]
@DarkFranX Thanks for reporting the problem.  What's the docker version on your node? Can you provide the commands/output to reproduce this problem?

**Comment by francisjeanneau** [comment]
@dongluochen Basically, I set up the swarm with virtualbox and consul discovery according to this tutorial: http://blog.scottlowe.org/2015/03/06/running-own-docker-swarm-cluster/

**Docker engine version:** 1.10.3
**Swarm image version:** 1.2.0rc1

And I am also using docker-py 1.8.0-dev to communicate with Docker API.

Steps to reproduce:
1. `docker -H=tcp://192.168.33.11:3375 run -v /path/to/file.txt:/container/path/to/file.txt:Z iron/gcc:dev sh -c "cat /container/path/to/file.txt"`
2. Edit file.txt
3. `docker -H=tcp://192.168.33.11:3375 run -v /path/to/file.txt:/container/path/to/file.txt:Z iron/gcc:dev sh -c "cat /container/path/to/file.txt"`

Second command should output wrong data.
That happens whether you communicate with Swarm Manager or directly with a node.

### Example:

**With file.txt:**

```
 /* Hello World program */

#include<stdio.h>

int main()
{
    printf("Hello World");
}
```

IN:
 `docker -H=tcp://192.168.33.11:3375 run -v /path/to/file.txt:/container/path/to/file.txt:Z iron/gcc:dev sh -c "cat /container/path/to/file.txt"`

OUT: 

```
 /* Hello World program */

#include<stdio.h>

int main()
{
    printf("Hello World");
}
```

**Edit file.txt by removing couple lines at the top and save:**

```
int main()
{
    printf("Hello World");
}
```

**Then retry to bind it in the container:**

IN:
 `docker -H=tcp://192.168.33.11:3375 run -v /path/to/file.txt:/container/path/to/file.txt:Z iron/gcc:dev sh -c "cat /container/path/to/file.txt"`

OUT:

```
/* Hello World program */

#include<stdio.
```

**Comment by dongluochen** [comment]
@DarkFranX I didn't realize we are at https://github.com/docker/swarm-library-image/ branch. This is not the right repo for swarm or docker usage issues. I suspect this problem is with docker-py, if that's the case you should open issue on https://github.com/docker/docker-py/. If you can reproduce this problem with Docker CLI on Docker Engine, open an issue on https://github.com/docker/docker. If it's a Swarm specific issue, do that at https://github.com/docker/swarm.

**Comment by francisjeanneau** [comment]
Alright, I will forward to Swarm issues.
