### ISSUE TITLE
'pending' status on all nodes

### ISSUE THREAD

**Issue by qiankunli** [docker/swarm-library-image#9]
I got 'pending' status on all nodes expect the node which run the swarm manager.

docker swarm version : 1.2.3
docker version : 1.7.1 
OS : CentOS6

![2](https://cloud.githubusercontent.com/assets/8024725/15664933/536f9838-273a-11e6-9a15-8e555084e193.png)

**Comment by dongluochen** [comment]
@qiankunli This repo is for swarm release only. Please use https://github.com/docker/swarm for swarm related issues. 

For your specific problem here. Swarm doesn't support Docker Engine 1.7.1 because it lacks the support for `event` API. See https://github.com/docker/swarm/pull/2331.
